/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.kestraa.crud[D[D[D[D[C[C[C[C[D[D[D[D[D[C[C[C[C[C

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testAppHasAGreeting() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
