/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.kestraa.crud[D[D[D[D[C[C[C[C[D[D[D[D[D[C[C[C[C[C

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main(args: Array<String>) {
    println(App().greeting)
}
